apiVersion: apps/v1
kind: Deployment # K8s resource kind we are creating
metadata:
  name: spring-boot-k8s
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 3 # Number of replicas (pods) that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: spring-k8s:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent # If not present at local, it will search at docker hub
          ports:
            - containerPort: 8080 #


