FROM openjdk:8
EXPOSE 8080
ADD build/libs/SpringBootKubernetesApplication-0.0.1-SNAPSHOT.jar SpringBootKubernetesApplication-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/SpringK8sJar-0.0.1-SNAPSHOT.jar"]
